tabWidth: 2
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: none
bracketSpacing: false
bracketSameLine: true
arrowParens: always
singleAttributePerLine: true

phpVersion: '8.2'
plugins:
  - '@prettier/plugin-php'
